{{- $defaults := . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "21600"
    nginx.ingress.kubernetes.io/eventsource: "true"
spec:
  rules:
    - host: ms.krolebord.online
      http:
        paths:
          {{- range $index, $value := .Values.microservises }}
          {{- $_ := set $value "nameOverride" $index }}
          {{- $microservice := dict "Values" $value }}
          {{- $defaultsCopy := $defaults | deepCopy }}
          {{- with mergeOverwrite $defaultsCopy $microservice }}
          {{- if $value.ingress.sse }}}
          - path: {{ $value.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "common.fullname" . }}
                port:
                  name: {{ $value.ingress.port }}
          {{- end -}}
          {{- end -}}
          {{- end -}}
