name: "Build and Publish to Docker"
description: "Pushes built artifacts to Docker"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
  tags:
    description: “Tags for image”
    required: true
  name:
    description: "Service name"
    required: true
  migrator_tags:
    description: "Tag for migrator image"
    required: false

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: ./services
          file: ./services/${{inputs.name}}/Dockerfile
          push: true
          tags: ${{inputs.tags}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build migrator base
        if: ${{inputs.migrator_tags}}
        uses: docker/build-push-action@v3
        with:
          tags: ms-migrator:latest
          context: ./services/Migrator
          file: ./services/Migrator/Dockerfile
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: List images
        shell: bash
        run: docker image ls -a
      - name: Build migrator
        if: ${{inputs.migrator_tags}}
        uses: docker/build-push-action@v3
        with:
          tags: ${{inputs.migrator_tags}}
          context: ./services
          file: ./services/${{inputs.name}}/Dockerfile
          push: true
          target: migrator
          cache-from: type=gha
          cache-to: type=gha,mode=max
