name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      client: ${{ steps.filter.outputs.client }}
      migrator: ${{ steps.filter.outputs.migrator }}
      services: ${{ steps.filter.outputs.services }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          client:
            - 'client/**'
          migrator:
            - 'services/Migrator/**'
          services:
            - 'services/**'

  publish-client:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:client
          context: ./client
          file: ./client/Dockerfile

  publish-migrator:
    runs-on: ubuntu-latest
    needs: changes
    # if: ${{ needs.changes.outputs.migrator == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:migrator
          context: ./services/Migrator
          file: ./services/Migrator/Dockerfile


  publish-auth-service:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:auth
          context: ./services
          file: ./services/AuthService/Dockerfile

  publish-auth-service-migrator:
    runs-on: ubuntu-latest
    needs: [changes, publish-migrator]
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:auth-migrator
          context: ./services
          file: ./services/AuthService/Dockerfile
          target: migrator


  publish-user-service:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:user
          context: ./services
          file: ./services/UserService/Dockerfile
  
  publish-user-service-migrator:
    runs-on: ubuntu-latest
    needs: [changes, publish-migrator]
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:user-migrator
          context: ./services
          file: ./services/UserService/Dockerfile
          target: migrator


  publish-post-service:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:post
          context: ./services
          file: ./services/PostService/Dockerfile

  publish-post-service-migrator:
    runs-on: ubuntu-latest
    needs: [changes, publish-migrator]
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:post-migrator
          context: ./services
          file: ./services/PostService/Dockerfile
          target: migrator


  publish-timeline-service:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:timeline
          context: ./services
          file: ./services/TimelineService/Dockerfile

  publish-notifications-service:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:notifications
          context: ./services
          file: ./services/NotificationsService/Dockerfile

  publish-notifications-service-migrator:
    runs-on: ubuntu-latest
    needs: [changes, publish-migrator]
    # if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:notifications-migrator
          context: ./services
          file: ./services/NotificationsService/Dockerfile
          target: migrator


  publish-notifier-service:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.services == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:notifier
          context: ./services
          file: ./services/NotifierService/Dockerfile
