name: Build and Push

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  publish-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:client
          context: ./client
          file: ./client/Dockerfile

  publish-auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-service
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:auth
          migrator_tags: mianni/ms-services:auth-migrator
          name: AuthService

  publish-user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-service
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:user
          migrator_tags: mianni/ms-services:user-migrator
          name: UserService

  publish-post-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-service
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:post
          migrator_tags: mianni/ms-services:post-migrator
          name: PostService

  publish-timeline-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-service
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:timeline
          migrator_tags: mianni/ms-services:timeline-migrator
          name: TimelineService
  