name: Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  publish-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:client
          context: ./client
          file: ./client/Dockerfile

  build-migrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Frontend
        uses: docker/build-push-action@v3
        with:
          tags: tatihutii/easymeets_frontend:latest
          context: ./services/Migrator
          file: ./services/Migrator/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max


  publish-auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:auth
          context: ./services
          file: ./services/AuthService/Dockerfile

  publish-auth-service-migrator:
    runs-on: ubuntu-latest
    needs: build-migrator
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:auth-migrator
          context: ./services
          file: ./services/AuthService/Dockerfile
          target: migrator


  publish-user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:user
          context: ./services
          file: ./services/UserService/Dockerfile
  
  publish-user-service-migrator:
    runs-on: ubuntu-latest
    needs: build-migrator
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:user-migrator
          context: ./services
          file: ./services/UserService/Dockerfile
          target: migrator


  publish-post-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:post
          context: ./services
          file: ./services/PostService/Dockerfile

  publish-post-service-migrator:
    runs-on: ubuntu-latest
    needs: build-migrator
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:post-migrator
          context: ./services
          file: ./services/PostService/Dockerfile
          target: migrator


  publish-timeline-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          registry_username: ${{secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{secrets.DOCKERHUB_TOKEN}}
          tags: mianni/ms-services:timeline
          context: ./services
          file: ./services/TimelineService/Dockerfile
